name: Integration

on:
    pull_request:
        branches: [main]

permissions:
    contents: read

jobs:
    depcheck:
        name: Testing Depcheck

        runs-on: ubuntu-latest
        steps:
            - name: Setup Node environment
              uses: actions/checkout@v3
              with:
                  node-version: 18.16.0
                  package-manager: pnpm
                  package-manager-version: 8.6.12

            - name: Test Depcheck
              run: pnpm run depcheck

    typescript:
        name: Testing TypeScript

        runs-on: ubuntu-latest
        steps:
            - name: Setup Node environment
              uses: actions/checkout@v3
              with:
                  node-version: 18.16.0
                  package-manager: pnpm
                  package-manager-version: 8.6.12

            - name: Test TypeScript
              run: pnpm run type-check

    prettier:
        name: Testing Prettier

        runs-on: ubuntu-latest
        steps:
            - name: Setup Node environment
              uses: actions/checkout@v3
              with:
                  node-version: 18.16.0
                  package-manager: pnpm
                  package-manager-version: 8.6.12

            - name: Test Prettier
              run: pnpm prettier

    eslint:
        name: Testing ESLint

        runs-on: ubuntu-latest
        steps:
            - name: Setup Node environment
              uses: actions/checkout@v3
              with:
                  node-version: 18.16.0
                  package-manager: pnpm
                  package-manager-version: 8.6.12

            - name: Test ESLint
              run: pnpm lint

    stylelint:
        name: Testing Stylelint

        runs-on: ubuntu-latest
        steps:
            - name: Setup Node environment
              uses: actions/checkout@v3
              with:
                  node-version: 18.16.0
                  package-manager: pnpm
                  package-manager-version: 8.6.12

            - name: Test Stylelint
              run: pnpm stylelint

    build:
        name: Testing build

        runs-on: ubuntu-latest
        steps:
            - name: Setup Node environment
              uses: actions/checkout@v3
              with:
                  node-version: 18.17.0
                  package-manager: pnpm
                  package-manager-version: 8.6.12

            - name: Test build
              run: pnpm build